### ISSUE TITLE
Using ip2proxy-ruby gem with  ip2location-ruby gem in one project

### ISSUE THREAD

**Issue by durcak** [ip2location/ip2proxy-ruby#1]
Hi, I have problem with using ip2proxy-ruby gem with  ip2location-ruby gem in one project, I get error:
/usr/local/rvm/gems/ruby-2.3.0/gems/ip2proxy_ruby-1.0.1/lib/ip2proxy_ruby/database_config.rb:2: warning: already initialized constant DbConfig::COLUMNS
/usr/local/rvm/gems/ruby-2.3.0/gems/ip2location_ruby-8.0.1/lib/ip2location_ruby/database_config.rb:2: warning: previous definition of COLUMNS was here
or 
/usr/local/rvm/gems/ruby-2.3.0/gems/ip2proxy_ruby-1.0.1/lib/ip2proxy_ruby/database_config.rb:13:in `block in setup_database': undefined method `>' for nil:NilClass (NoMethodError)
Can you help me with that please? Thanks

**Comment by durcak** [comment]
Hi I solve this problem with "require: false" in gemfile, but I have another problem:
readbytes': data truncated. It looks like gems share their databases or data :/ Can you 
 help me please? Thanks

`/usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/io.rb:279:in `readbytes': data truncated (IOError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/string.rb:118:in `read_and_return_value'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/base_primitive.rb:127:in `do_read'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/base.rb:147:in `block in read'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/base.rb:254:in `start_read'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/base.rb:145:in `read'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/ip2proxy_ruby-1.0.1/lib/ip2proxy_ruby/i2p_string_data.rb:11:in `read_and_return_value'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/base_primitive.rb:127:in `do_read'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/struct.rb:138:in `block in do_read'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/struct.rb:138:in `each'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/struct.rb:138:in `do_read'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/base.rb:147:in `block in read'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/base.rb:254:in `start_read'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/base.rb:145:in `read'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bindata-2.3.5/lib/bindata/base.rb:21:in `read'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/ip2proxy_ruby-1.0.1/lib/ip2proxy_ruby.rb:245:in `bsearch'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/ip2proxy_ruby-1.0.1/lib/ip2proxy_ruby.rb:74:in `get_record'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/ip2proxy_ruby-1.0.1/lib/ip2proxy_ruby.rb:192:in `getAll'
	from /home/tomas/Plocha/Diplomka/ip2lite/proxy.rb:14:in `block (2 levels) in <main>'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1748:in `each'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1131:in `block in foreach'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1282:in `open'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1130:in `foreach'
	from /home/tomas/Plocha/Diplomka/ip2lite/proxy.rb:12:in `block in <main>'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/csv.rb:1282:in `open'`

**Comment by ip2location-com** [comment]
Hi @durcak 
We have updated our code to fix this issue.
